// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bad.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bad struct {
	Command              int32    `protobuf:"varint,1,opt,name=Command,proto3" json:"Command,omitempty"`
	SubCommand           int32    `protobuf:"varint,2,opt,name=SubCommand,proto3" json:"SubCommand,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bad) Reset()         { *m = Bad{} }
func (m *Bad) String() string { return proto.CompactTextString(m) }
func (*Bad) ProtoMessage()    {}
func (*Bad) Descriptor() ([]byte, []int) {
	return fileDescriptor_488ac25a43dcd766, []int{0}
}

func (m *Bad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bad.Unmarshal(m, b)
}
func (m *Bad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bad.Marshal(b, m, deterministic)
}
func (m *Bad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bad.Merge(m, src)
}
func (m *Bad) XXX_Size() int {
	return xxx_messageInfo_Bad.Size(m)
}
func (m *Bad) XXX_DiscardUnknown() {
	xxx_messageInfo_Bad.DiscardUnknown(m)
}

var xxx_messageInfo_Bad proto.InternalMessageInfo

func (m *Bad) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *Bad) GetSubCommand() int32 {
	if m != nil {
		return m.SubCommand
	}
	return 0
}

func (m *Bad) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Bad) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Bad)(nil), "pb.Bad")
}

func init() { proto.RegisterFile("bad.proto", fileDescriptor_488ac25a43dcd766) }

var fileDescriptor_488ac25a43dcd766 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4a, 0x4c, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xca, 0xe5, 0x62, 0x76, 0x4a, 0x4c,
	0x11, 0x92, 0xe0, 0x62, 0x77, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x82, 0x71, 0x85, 0xe4, 0xb8, 0xb8, 0x82, 0x4b, 0x93, 0x60, 0x92, 0x4c, 0x60, 0x49,
	0x24, 0x11, 0x21, 0x21, 0x2e, 0x16, 0xe7, 0xfc, 0x94, 0x54, 0x09, 0x66, 0xb0, 0x0c, 0x98, 0x0d,
	0x32, 0xcd, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x45, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xc6, 0x4d, 0x62, 0x03, 0xdb, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xef, 0x02, 0xcd,
	0x86, 0x00, 0x00, 0x00,
}
