// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	SID                  string   `protobuf:"bytes,1,opt,name=SID,proto3" json:"SID,omitempty"`
	UserID               uint64   `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	V                    int32    `protobuf:"varint,3,opt,name=V,proto3" json:"V,omitempty"`
	From                 int32    `protobuf:"varint,4,opt,name=From,proto3" json:"From,omitempty"`
	FromAddress          string   `protobuf:"bytes,5,opt,name=FromAddress,proto3" json:"FromAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetSID() string {
	if m != nil {
		return m.SID
	}
	return ""
}

func (m *Header) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Header) GetV() int32 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *Header) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Header) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

type Request struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Command              int32    `protobuf:"varint,2,opt,name=Command,proto3" json:"Command,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Command              int32    `protobuf:"varint,1,opt,name=Command,proto3" json:"Command,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "pb.Header")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x9a, 0xa4, 0xe5, 0x12, 0x24, 0x74, 0x03, 0xb2, 0x98, 0x22, 0xb3, 0x84, 0x25,
	0x42, 0x65, 0x61, 0x85, 0x56, 0x88, 0xac, 0xae, 0xe8, 0x00, 0x93, 0x83, 0x6f, 0x40, 0x4a, 0xe2,
	0x60, 0x87, 0x4a, 0xfc, 0x7b, 0x14, 0xa7, 0x11, 0x19, 0x50, 0x27, 0xbf, 0xf7, 0xe4, 0x77, 0xf7,
	0xe9, 0xe0, 0xc2, 0x91, 0x3d, 0x7c, 0x7e, 0x50, 0xd1, 0x59, 0xd3, 0x1b, 0x0c, 0xba, 0x4a, 0x1c,
	0x20, 0x7e, 0x21, 0xa5, 0xc9, 0xe2, 0x25, 0x2c, 0x76, 0xe5, 0x96, 0xb3, 0x8c, 0xe5, 0xe7, 0x72,
	0x90, 0x78, 0x05, 0xf1, 0xab, 0x23, 0x5b, 0x6e, 0x79, 0x90, 0xb1, 0x3c, 0x94, 0x47, 0x87, 0x29,
	0xb0, 0x3d, 0x5f, 0x64, 0x2c, 0x8f, 0x24, 0xdb, 0x23, 0x42, 0xf8, 0x6c, 0x4d, 0xc3, 0x43, 0x1f,
	0x78, 0x8d, 0x19, 0x24, 0xc3, 0xfb, 0xa8, 0xb5, 0x25, 0xe7, 0x78, 0xe4, 0x67, 0xce, 0x23, 0xf1,
	0x0e, 0x4b, 0x49, 0x5f, 0xdf, 0xe4, 0x7a, 0x14, 0x13, 0x82, 0xdf, 0x9d, 0xac, 0xa1, 0xe8, 0xaa,
	0x62, 0x4c, 0xe4, 0x04, 0xc7, 0x61, 0xb9, 0x31, 0x4d, 0xa3, 0x5a, 0xed, 0x59, 0x22, 0x39, 0xd9,
	0x61, 0xfd, 0x93, 0xd1, 0x3f, 0x9e, 0x27, 0x95, 0x5e, 0x8b, 0x07, 0x58, 0x49, 0x72, 0x9d, 0x69,
	0x1d, 0xcd, 0x9b, 0xec, 0xff, 0x66, 0xf0, 0xd7, 0x5c, 0xbf, 0xc1, 0xaa, 0x6c, 0x7b, 0xb2, 0xad,
	0xaa, 0xf1, 0x06, 0xc2, 0x8d, 0xaa, 0x6b, 0x4c, 0x06, 0x9e, 0x23, 0xec, 0x75, 0x3a, 0x9a, 0x71,
	0xb8, 0x38, 0xc3, 0x5b, 0x88, 0x77, 0xbd, 0x25, 0xd5, 0x9c, 0xfc, 0x96, 0xb3, 0x3b, 0x56, 0xc5,
	0xfe, 0xea, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xfc, 0xa1, 0xc6, 0x86, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InternalClient is the client API for Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Internal_StreamClient, error)
}

type internalClient struct {
	cc *grpc.ClientConn
}

func NewInternalClient(cc *grpc.ClientConn) InternalClient {
	return &internalClient{cc}
}

func (c *internalClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Internal/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Internal_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Internal_serviceDesc.Streams[0], "/pb.Internal/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &internalStreamClient{stream}
	return x, nil
}

type Internal_StreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type internalStreamClient struct {
	grpc.ClientStream
}

func (x *internalStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *internalStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InternalServer is the server API for Internal service.
type InternalServer interface {
	Call(context.Context, *Request) (*Response, error)
	Stream(Internal_StreamServer) error
}

// UnimplementedInternalServer can be embedded to have forward compatible implementations.
type UnimplementedInternalServer struct {
}

func (*UnimplementedInternalServer) Call(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedInternalServer) Stream(srv Internal_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterInternalServer(s *grpc.Server, srv InternalServer) {
	s.RegisterService(&_Internal_serviceDesc, srv)
}

func _Internal_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Internal/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InternalServer).Stream(&internalStreamServer{stream})
}

type Internal_StreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type internalStreamServer struct {
	grpc.ServerStream
}

func (x *internalStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *internalStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Internal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Internal",
	HandlerType: (*InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Internal_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Internal_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
