// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionStateServerAPI struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStateServerAPI) Reset()         { *m = SessionStateServerAPI{} }
func (m *SessionStateServerAPI) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI) ProtoMessage()    {}
func (*SessionStateServerAPI) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *SessionStateServerAPI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI.Unmarshal(m, b)
}
func (m *SessionStateServerAPI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI.Merge(m, src)
}
func (m *SessionStateServerAPI) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI.Size(m)
}
func (m *SessionStateServerAPI) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI proto.InternalMessageInfo

type SessionStateServerAPI_Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStateServerAPI_Nil) Reset()         { *m = SessionStateServerAPI_Nil{} }
func (m *SessionStateServerAPI_Nil) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI_Nil) ProtoMessage()    {}
func (*SessionStateServerAPI_Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 0}
}

func (m *SessionStateServerAPI_Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI_Nil.Unmarshal(m, b)
}
func (m *SessionStateServerAPI_Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI_Nil.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI_Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI_Nil.Merge(m, src)
}
func (m *SessionStateServerAPI_Nil) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI_Nil.Size(m)
}
func (m *SessionStateServerAPI_Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI_Nil proto.InternalMessageInfo

type SessionStateServerAPI_Param struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStateServerAPI_Param) Reset()         { *m = SessionStateServerAPI_Param{} }
func (m *SessionStateServerAPI_Param) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI_Param) ProtoMessage()    {}
func (*SessionStateServerAPI_Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 1}
}

func (m *SessionStateServerAPI_Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI_Param.Unmarshal(m, b)
}
func (m *SessionStateServerAPI_Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI_Param.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI_Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI_Param.Merge(m, src)
}
func (m *SessionStateServerAPI_Param) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI_Param.Size(m)
}
func (m *SessionStateServerAPI_Param) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI_Param.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI_Param proto.InternalMessageInfo

func (m *SessionStateServerAPI_Param) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SessionStateServerAPI_Param) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SessionStateServerAPI_Event struct {
	Action               int32    `protobuf:"varint,1,opt,name=Action,proto3" json:"Action,omitempty"`
	UID                  uint64   `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStateServerAPI_Event) Reset()         { *m = SessionStateServerAPI_Event{} }
func (m *SessionStateServerAPI_Event) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI_Event) ProtoMessage()    {}
func (*SessionStateServerAPI_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 2}
}

func (m *SessionStateServerAPI_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI_Event.Unmarshal(m, b)
}
func (m *SessionStateServerAPI_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI_Event.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI_Event.Merge(m, src)
}
func (m *SessionStateServerAPI_Event) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI_Event.Size(m)
}
func (m *SessionStateServerAPI_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI_Event.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI_Event proto.InternalMessageInfo

func (m *SessionStateServerAPI_Event) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *SessionStateServerAPI_Event) GetUID() uint64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *SessionStateServerAPI_Event) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type SessionStateServerAPI_EventChangeParam struct {
	Values               []*SessionStateServerAPI_Param `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SessionStateServerAPI_EventChangeParam) Reset() {
	*m = SessionStateServerAPI_EventChangeParam{}
}
func (m *SessionStateServerAPI_EventChangeParam) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI_EventChangeParam) ProtoMessage()    {}
func (*SessionStateServerAPI_EventChangeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 3}
}

func (m *SessionStateServerAPI_EventChangeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI_EventChangeParam.Unmarshal(m, b)
}
func (m *SessionStateServerAPI_EventChangeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI_EventChangeParam.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI_EventChangeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI_EventChangeParam.Merge(m, src)
}
func (m *SessionStateServerAPI_EventChangeParam) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI_EventChangeParam.Size(m)
}
func (m *SessionStateServerAPI_EventChangeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI_EventChangeParam.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI_EventChangeParam proto.InternalMessageInfo

func (m *SessionStateServerAPI_EventChangeParam) GetValues() []*SessionStateServerAPI_Param {
	if m != nil {
		return m.Values
	}
	return nil
}

type SessionStateServerAPI_BroadcastRequest struct {
	Actions              []*SessionStateServerAPI_Event `protobuf:"bytes,1,rep,name=Actions,proto3" json:"Actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SessionStateServerAPI_BroadcastRequest) Reset() {
	*m = SessionStateServerAPI_BroadcastRequest{}
}
func (m *SessionStateServerAPI_BroadcastRequest) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI_BroadcastRequest) ProtoMessage()    {}
func (*SessionStateServerAPI_BroadcastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 4}
}

func (m *SessionStateServerAPI_BroadcastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI_BroadcastRequest.Unmarshal(m, b)
}
func (m *SessionStateServerAPI_BroadcastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI_BroadcastRequest.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI_BroadcastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI_BroadcastRequest.Merge(m, src)
}
func (m *SessionStateServerAPI_BroadcastRequest) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI_BroadcastRequest.Size(m)
}
func (m *SessionStateServerAPI_BroadcastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI_BroadcastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI_BroadcastRequest proto.InternalMessageInfo

func (m *SessionStateServerAPI_BroadcastRequest) GetActions() []*SessionStateServerAPI_Event {
	if m != nil {
		return m.Actions
	}
	return nil
}

type SessionStateServerAPI_BroadcastResponse struct {
	Actions              []*SessionStateServerAPI_Event `protobuf:"bytes,1,rep,name=Actions,proto3" json:"Actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SessionStateServerAPI_BroadcastResponse) Reset() {
	*m = SessionStateServerAPI_BroadcastResponse{}
}
func (m *SessionStateServerAPI_BroadcastResponse) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI_BroadcastResponse) ProtoMessage()    {}
func (*SessionStateServerAPI_BroadcastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 5}
}

func (m *SessionStateServerAPI_BroadcastResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI_BroadcastResponse.Unmarshal(m, b)
}
func (m *SessionStateServerAPI_BroadcastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI_BroadcastResponse.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI_BroadcastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI_BroadcastResponse.Merge(m, src)
}
func (m *SessionStateServerAPI_BroadcastResponse) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI_BroadcastResponse.Size(m)
}
func (m *SessionStateServerAPI_BroadcastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI_BroadcastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI_BroadcastResponse proto.InternalMessageInfo

func (m *SessionStateServerAPI_BroadcastResponse) GetActions() []*SessionStateServerAPI_Event {
	if m != nil {
		return m.Actions
	}
	return nil
}

type SessionStateServerAPI_NewRequest struct {
	UID                  uint64                         `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Params               []*SessionStateServerAPI_Param `protobuf:"bytes,2,rep,name=Params,proto3" json:"Params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SessionStateServerAPI_NewRequest) Reset()         { *m = SessionStateServerAPI_NewRequest{} }
func (m *SessionStateServerAPI_NewRequest) String() string { return proto.CompactTextString(m) }
func (*SessionStateServerAPI_NewRequest) ProtoMessage()    {}
func (*SessionStateServerAPI_NewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0, 6}
}

func (m *SessionStateServerAPI_NewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStateServerAPI_NewRequest.Unmarshal(m, b)
}
func (m *SessionStateServerAPI_NewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStateServerAPI_NewRequest.Marshal(b, m, deterministic)
}
func (m *SessionStateServerAPI_NewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStateServerAPI_NewRequest.Merge(m, src)
}
func (m *SessionStateServerAPI_NewRequest) XXX_Size() int {
	return xxx_messageInfo_SessionStateServerAPI_NewRequest.Size(m)
}
func (m *SessionStateServerAPI_NewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStateServerAPI_NewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStateServerAPI_NewRequest proto.InternalMessageInfo

func (m *SessionStateServerAPI_NewRequest) GetUID() uint64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *SessionStateServerAPI_NewRequest) GetParams() []*SessionStateServerAPI_Param {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionStateServerAPI)(nil), "pb.SessionStateServerAPI")
	proto.RegisterType((*SessionStateServerAPI_Nil)(nil), "pb.SessionStateServerAPI.Nil")
	proto.RegisterType((*SessionStateServerAPI_Param)(nil), "pb.SessionStateServerAPI.Param")
	proto.RegisterType((*SessionStateServerAPI_Event)(nil), "pb.SessionStateServerAPI.Event")
	proto.RegisterType((*SessionStateServerAPI_EventChangeParam)(nil), "pb.SessionStateServerAPI.EventChangeParam")
	proto.RegisterType((*SessionStateServerAPI_BroadcastRequest)(nil), "pb.SessionStateServerAPI.BroadcastRequest")
	proto.RegisterType((*SessionStateServerAPI_BroadcastResponse)(nil), "pb.SessionStateServerAPI.BroadcastResponse")
	proto.RegisterType((*SessionStateServerAPI_NewRequest)(nil), "pb.SessionStateServerAPI.NewRequest")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x4f, 0xe2, 0x40,
	0x14, 0xc7, 0x29, 0xa5, 0xdd, 0xf0, 0x76, 0x37, 0x61, 0x5f, 0x76, 0x37, 0x4d, 0x13, 0x23, 0x21,
	0x1e, 0x1a, 0x4d, 0xaa, 0xc1, 0x03, 0xf1, 0x08, 0xca, 0x81, 0xa8, 0x95, 0x4c, 0xa3, 0x9e, 0x3c,
	0xb4, 0xe5, 0xa9, 0x8d, 0xd0, 0xa9, 0x9d, 0x52, 0xc2, 0x67, 0xf4, 0x23, 0xf8, 0x65, 0x4c, 0xa7,
	0x80, 0x26, 0x08, 0xc1, 0xc8, 0xed, 0x4d, 0xe6, 0xbd, 0xdf, 0xfc, 0xff, 0xff, 0x97, 0x81, 0xdf,
	0x82, 0x92, 0x2c, 0x0c, 0xc8, 0x8e, 0x13, 0x9e, 0x72, 0x2c, 0xc7, 0x7e, 0xe3, 0x55, 0x85, 0x7f,
	0x2e, 0x09, 0x11, 0xf2, 0xc8, 0x4d, 0xbd, 0x94, 0x5c, 0x4a, 0x32, 0x4a, 0xda, 0xfd, 0x9e, 0xa9,
	0x81, 0xea, 0x84, 0x43, 0xf3, 0x10, 0xb4, 0xbe, 0x97, 0x78, 0x23, 0xac, 0x81, 0xfa, 0x44, 0x53,
	0x43, 0xa9, 0x2b, 0x56, 0x95, 0xe5, 0x25, 0xfe, 0x05, 0xed, 0xc6, 0x1b, 0x8e, 0xc9, 0x28, 0xd7,
	0x15, 0xeb, 0x17, 0x2b, 0x0e, 0x66, 0x17, 0xb4, 0x6e, 0x46, 0x51, 0x8a, 0xff, 0x41, 0x6f, 0x07,
	0x69, 0xc8, 0x23, 0x39, 0xa3, 0xb1, 0xd9, 0x29, 0x07, 0x5d, 0xf7, 0xce, 0xe4, 0x50, 0x85, 0xe5,
	0x25, 0x22, 0x54, 0x3a, 0x7c, 0x30, 0x35, 0x54, 0xc9, 0x91, 0xb5, 0x79, 0x0e, 0x35, 0x89, 0x39,
	0x7d, 0xf4, 0xa2, 0x07, 0x2a, 0x24, 0xb4, 0x40, 0x97, 0x6f, 0x08, 0x43, 0xa9, 0xab, 0xd6, 0xcf,
	0xe6, 0xae, 0x1d, 0xfb, 0xf6, 0xa7, 0xea, 0x6d, 0x39, 0xc0, 0x66, 0xed, 0xe6, 0x25, 0xd4, 0x3a,
	0x09, 0xf7, 0x06, 0x81, 0x27, 0x52, 0x46, 0xcf, 0x63, 0x12, 0x29, 0x9e, 0xc0, 0x8f, 0x42, 0xd0,
	0x06, 0x34, 0xa9, 0x84, 0xcd, 0xfb, 0x4d, 0x07, 0xfe, 0x7c, 0xc0, 0x89, 0x98, 0x47, 0x82, 0xbe,
	0xc3, 0xbb, 0x05, 0x70, 0x68, 0x32, 0x17, 0x36, 0xcb, 0x47, 0x79, 0xcf, 0xa7, 0x05, 0xba, 0xf4,
	0x23, 0x8c, 0xf2, 0x86, 0xbe, 0x8b, 0xf6, 0xe6, 0x8b, 0x0a, 0xb8, 0xdc, 0x87, 0x77, 0x50, 0x75,
	0xc7, 0xbe, 0x08, 0x92, 0xd0, 0x27, 0xdc, 0x59, 0x0d, 0xcb, 0xf7, 0x7f, 0xb0, 0xfa, 0x7a, 0x29,
	0x83, 0x46, 0xc9, 0x52, 0x8e, 0x14, 0xbc, 0x87, 0xea, 0xe2, 0x0a, 0xf7, 0x37, 0x9a, 0x97, 0xce,
	0xbf, 0xf8, 0x16, 0x5e, 0x80, 0xea, 0xd0, 0x04, 0xf7, 0xd6, 0x18, 0x58, 0xa4, 0x6a, 0xae, 0xb7,
	0xd9, 0x28, 0xe1, 0x15, 0xe8, 0x8c, 0x46, 0x3c, 0xa3, 0x2d, 0x02, 0x8b, 0x35, 0x6c, 0x09, 0xe8,
	0xeb, 0xf2, 0xdb, 0x1e, 0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x29, 0x99, 0x46, 0xc7, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SessionStateServerClient is the client API for SessionStateServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionStateServerClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (SessionStateServer_SubscribeClient, error)
	Broadcast(ctx context.Context, in *SessionStateServerAPI_BroadcastRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_BroadcastResponse, error)
	New(ctx context.Context, in *SessionStateServerAPI_NewRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_Nil, error)
	Remove(ctx context.Context, in *SessionStateServerAPI_NewRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_Nil, error)
	Params(ctx context.Context, in *SessionStateServerAPI_NewRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_Nil, error)
}

type sessionStateServerClient struct {
	cc *grpc.ClientConn
}

func NewSessionStateServerClient(cc *grpc.ClientConn) SessionStateServerClient {
	return &sessionStateServerClient{cc}
}

func (c *sessionStateServerClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (SessionStateServer_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SessionStateServer_serviceDesc.Streams[0], "/pb.SessionStateServer/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionStateServerSubscribeClient{stream}
	return x, nil
}

type SessionStateServer_SubscribeClient interface {
	Send(*SessionStateServerAPI_Nil) error
	Recv() (*SessionStateServerAPI_BroadcastResponse, error)
	grpc.ClientStream
}

type sessionStateServerSubscribeClient struct {
	grpc.ClientStream
}

func (x *sessionStateServerSubscribeClient) Send(m *SessionStateServerAPI_Nil) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sessionStateServerSubscribeClient) Recv() (*SessionStateServerAPI_BroadcastResponse, error) {
	m := new(SessionStateServerAPI_BroadcastResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sessionStateServerClient) Broadcast(ctx context.Context, in *SessionStateServerAPI_BroadcastRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_BroadcastResponse, error) {
	out := new(SessionStateServerAPI_BroadcastResponse)
	err := c.cc.Invoke(ctx, "/pb.SessionStateServer/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStateServerClient) New(ctx context.Context, in *SessionStateServerAPI_NewRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_Nil, error) {
	out := new(SessionStateServerAPI_Nil)
	err := c.cc.Invoke(ctx, "/pb.SessionStateServer/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStateServerClient) Remove(ctx context.Context, in *SessionStateServerAPI_NewRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_Nil, error) {
	out := new(SessionStateServerAPI_Nil)
	err := c.cc.Invoke(ctx, "/pb.SessionStateServer/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionStateServerClient) Params(ctx context.Context, in *SessionStateServerAPI_NewRequest, opts ...grpc.CallOption) (*SessionStateServerAPI_Nil, error) {
	out := new(SessionStateServerAPI_Nil)
	err := c.cc.Invoke(ctx, "/pb.SessionStateServer/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionStateServerServer is the server API for SessionStateServer service.
type SessionStateServerServer interface {
	Subscribe(SessionStateServer_SubscribeServer) error
	Broadcast(context.Context, *SessionStateServerAPI_BroadcastRequest) (*SessionStateServerAPI_BroadcastResponse, error)
	New(context.Context, *SessionStateServerAPI_NewRequest) (*SessionStateServerAPI_Nil, error)
	Remove(context.Context, *SessionStateServerAPI_NewRequest) (*SessionStateServerAPI_Nil, error)
	Params(context.Context, *SessionStateServerAPI_NewRequest) (*SessionStateServerAPI_Nil, error)
}

// UnimplementedSessionStateServerServer can be embedded to have forward compatible implementations.
type UnimplementedSessionStateServerServer struct {
}

func (*UnimplementedSessionStateServerServer) Subscribe(srv SessionStateServer_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedSessionStateServerServer) Broadcast(ctx context.Context, req *SessionStateServerAPI_BroadcastRequest) (*SessionStateServerAPI_BroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (*UnimplementedSessionStateServerServer) New(ctx context.Context, req *SessionStateServerAPI_NewRequest) (*SessionStateServerAPI_Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method New not implemented")
}
func (*UnimplementedSessionStateServerServer) Remove(ctx context.Context, req *SessionStateServerAPI_NewRequest) (*SessionStateServerAPI_Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedSessionStateServerServer) Params(ctx context.Context, req *SessionStateServerAPI_NewRequest) (*SessionStateServerAPI_Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterSessionStateServerServer(s *grpc.Server, srv SessionStateServerServer) {
	s.RegisterService(&_SessionStateServer_serviceDesc, srv)
}

func _SessionStateServer_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SessionStateServerServer).Subscribe(&sessionStateServerSubscribeServer{stream})
}

type SessionStateServer_SubscribeServer interface {
	Send(*SessionStateServerAPI_BroadcastResponse) error
	Recv() (*SessionStateServerAPI_Nil, error)
	grpc.ServerStream
}

type sessionStateServerSubscribeServer struct {
	grpc.ServerStream
}

func (x *sessionStateServerSubscribeServer) Send(m *SessionStateServerAPI_BroadcastResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sessionStateServerSubscribeServer) Recv() (*SessionStateServerAPI_Nil, error) {
	m := new(SessionStateServerAPI_Nil)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SessionStateServer_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStateServerAPI_BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStateServerServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SessionStateServer/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStateServerServer).Broadcast(ctx, req.(*SessionStateServerAPI_BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStateServer_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStateServerAPI_NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStateServerServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SessionStateServer/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStateServerServer).New(ctx, req.(*SessionStateServerAPI_NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStateServer_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStateServerAPI_NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStateServerServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SessionStateServer/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStateServerServer).Remove(ctx, req.(*SessionStateServerAPI_NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionStateServer_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStateServerAPI_NewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionStateServerServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SessionStateServer/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionStateServerServer).Params(ctx, req.(*SessionStateServerAPI_NewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionStateServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SessionStateServer",
	HandlerType: (*SessionStateServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _SessionStateServer_Broadcast_Handler,
		},
		{
			MethodName: "New",
			Handler:    _SessionStateServer_New_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _SessionStateServer_Remove_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _SessionStateServer_Params_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SessionStateServer_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
